### ISSUE TITLE
dll problem

### ISSUE THREAD

**Issue by wizardmanperson** [lnx00/Fedoraloader#1] opened 2022-04-13 19:17 UTC
The loader seems to be downloading the wrong version of Fedoraware. I can tell this is happening because its not loading the new features that got released into the cheat (material editor for example). If there is anyway I can fix this,
![error](https://user-images.githubusercontent.com/100414869/163253816-51377bc5-c22a-4f94-9225-09e4df2c8ff7.PNG)
 please let me know.

**Comment by TheLB13** [comment] 2022-04-13 23:34
yea me too

**Comment by lnx00** [comment] 2022-04-14 09:40
I've just checked it and it seems like https://nightly.link/ is causing this issue.
We need to use https://nightly.link/ to download the latest Fedoraware DLL, but for some reason it's stuck at the release from 11.04.2022

I will see what I can do about this

**Comment by TheLB13** [comment] 2022-04-15 05:57
no fix?

**Comment by ShiroSeby** [comment] 2022-04-15 08:45
> no fix?

You can build the .dll yourself instead of waiting for this to be fixed

**Comment by xxmyn** [comment] 2022-04-18 06:59
![image](https://user-images.githubusercontent.com/70382582/163768703-6cbf36dd-86ae-4b07-98d8-2368de38da08.png)

caused by this, last commit marked as success was [e9e47f2](https://github.com/tf2cheater2013/Fedoraware/commit/e9e47f2c0a4a5e8306fbe59f5b185d6089f9dd1a), [nightly.link knows about this btw](https://github.com/oprypin/nightly.link/issues/26).

For now I'd recommend you use your own injected & download the dll manually, until github fixes the issue.

**Closed** 2022-04-20 12:15 UTC
