### ISSUE TITLE
Central directory not found

### ISSUE THREAD

**Issue by FFJ11** [lnx00/Fedoraloader#19] opened 2022-07-04 10:17 UTC
![image](https://user-images.githubusercontent.com/102504389/177134700-6ec5bf6a-2383-4277-850d-646386b4b063.png)

**Comment by xxmyn** [comment] 2022-07-04 10:21
this issue is caused by a recent transfer of the repo, please be patient while lnx fixes it

**Comment by THEMASTEROFALL3** [comment] 2022-07-04 13:23
is there an eta or a discord i could possibly join to see when it gets fixed?

**Comment by lnx00** [comment] 2022-07-04 16:46
Fixed in the newest version:
https://github.com/lnx00/Fedoraloader/releases/latest/

**Closed by lnx00** 2022-07-04 16:46 UTC
